### ISSUE TITLE
Speicherkarte wird seit MacOS 13 (Ventura) nicht mehr erkannt

### ISSUE THREAD

**Issue by ralph** [winzkigermany/hoerbert-software#10]
Hallo!

Ich wollte gerade eine neue Speicherkarte für den Hörbert beschreiben, allerdings erkennt die Hörbert-Software die Speicherkarte nicht mehr. Ich habe mehrere Speicherkarten ausprobiert, die zuvor alle funktioniert haben, und keine wird von der Software mehr erkannt. Die letzte Speicherkarte habe ich mit MacOS 12 beschrieben, deshalb habe ich die Vermutung, dass es an MacOS 13 liegt. Gibt es mit dieser Version bekannte Probleme? Gibt es einen Workaround? Zugriff auf Speichermedien ist jedenfalls gewährt.

<img width="1611" alt="Bildschirm­foto 2022-11-22 um 10 19 19" src="https://user-images.githubusercontent.com/2190/203275485-acfd4d95-231c-431b-ad8e-838b7ad4b535.png">

Viele Grüße
Ralph

**Comment by winzkigermany** [comment]
Hallo Ralph,
das wurde gefixed, nur bin ich zu spät dran, das Update überall zu kommunizieren, sorry.
(Unsere Insolvenz war der Grund, aber jetzt geht es unter neuer Firma mit hörbert weiter!)
https://www.hoerbert.com/downloads/3.1.4/hoerbert_install.dmg
