### ISSUE TITLE
Please consider running "git tag" for the latest release

### ISSUE THREAD

**Issue by josch** [winzkigermany/hoerbert-software#20]
Hi,

I'm packaging `hoerbert-software` for the Debian Linux distribution from where it would then migrate to and also be easy to install on the more popular Ubuntu Linux distribution. I hope doing so has your blessing.

That being said, the version in the default git branch "main" as wells as the version exposed via the github releases is still at 2.1.5 while at https://en.hoerbert.com/customer-service/downloads-and-questions-about-transferring-contents/ Linux AppImages for version 3.1.3 are offered for download.

I saw that the branch "feedback" carries these newer versions.

Could you maybe consider running "git tag" on one of the later releases in the "feedback" branch? It is much easier to package something for a distribution if it is marked as a release either by a "git tag" or has an actual github release. The latter is a bit more work than just running "git tag" but just a "git tag" is sufficient for me. If you do a release on top of the tagging that that's also nice but not required.

Thank you for releasing your software under a FOSS license!

**Comment by winzkigermany** [comment]
Done for 3.1.4, hope that helps

**Comment by jmr** [comment]
> I'm packaging hoerbert-software for the Debian Linux distribution from where it would then migrate to and also be easy to install on the more popular Ubuntu Linux distribution

@josch I'm not sure what the debian requirements are, but it looks like there are blobs with no source.  See #15 .

**Comment by winzkigermany** [comment]
It would take me a bit to dig out the build parameters of the included subprojects... surely could do, but sadly not before christmas, which is a very busy time for us.

**Comment by josch** [comment]
> Done for 3.1.4, hope that helps

Thank you for the very quick response! Yes, that was exactly what I needed.

Unfortunately, there seem to be some files missing from git. According to `hoerbert/resources.qrc` the following files are missing from git:

 * images/rec_bt_active_512.png
 * images/rec_bt_inactive_512.png
 * images/rec_mic_active_512.png
 * images/rec_mic_inactive_512.png
 * images/rec_wifi_active_512.png
 * images/rec_wifi_inactive_512.png


> I'm not sure what the debian requirements are, but it looks like there are blobs with no source. See https://github.com/winzkigermany/hoerbert-software/issues/15 .

Yes, since these files are copyright violations of the GPL I just exclude them. The blobs are not useful for Debian anyways, since we want to use the packaged version of ffmpeg and not the blob shipped by hoerbert. This is even more so true since we will be shipping hoerbert for many different architectures. As an example, I am currently writing this on an ARM laptop, so the x86 intel blob is not useful here. :)

This is the copyright file I have so far:

```
Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
Source: https://github.com/winzkigermany/hoerbert-software
Files-Excluded:
 hoerbert/tools/linux
 hoerbert/tools/mac
 hoerbert/tools/windows
 hoerbert/tools/diagnostics/hoerbert.bak
 qtinstaller-windows

Files: *
Copyright: 2019, WINZKI GmbH & Co. KG
           Igor Yalovenko, Rainer Brang
License: GPL-3+

Files: hoerbert/waitingspinnerwidget.cpp
       hoerbert/waitingspinnerwidget.h
Copyright:
 2012-2014, Alexander Turkin
 2014 William Hallatt
 2015 Jacob Dawid
License: Expat
```

If you find any discrepancies of the stated licenses and copyright holders, please shout. :)

Thank you!

**Comment by winzkigermany** [comment]
Well, actually, WINZKI as a company is defunct - which has not been updated yet in the code.

The new owner is 
HMC Hightech Media Components GmbH & Co. KG

About the png files... I'll have to scrape the backups, no idea when or why they got lost.

**Comment by winzkigermany** [comment]
I've uploaded the missing png files.
The tag 3.1.4 is still missing these files, but I would rather not move the tag one commit ahead.
Since qt_resources.cpp contains the missing files anyways, only the original png files are missing from tag 3.1.4

**Comment by josch** [comment]
> I've uploaded the missing png files.

Thank you!! :heart:

Lets close this issue. Everything has been taken care of. :)
